/* File format information */
FILE                          = :TrackSections :TrackShapes .
FILE_NAME                     = "Track Sections (Global)" .
FILE_EXT                      = "tsection.dat" .
FILE_TYPE                     = "F" .
FILE_TYPE_VER                 = "0" .

/* Base types */
ClearanceDist                 ==> :float .
CrossoverShape                ==> .
FileName                      ==> :string .
MainRoute                     ==> :uint .
ManualJunctionShape           ==> .
NumPaths                      ==> :uint .
RoadShape                     ==> .
SectionCurve                  ==> :float,Radius :float,Angle .
SectionIdx                    ==> :uint,SectionCount :float,OffsetX :float,OffsetY :float,OffsetZ :float,RotateY {:uint} .
SectionSize                   ==> :float,Guage :float,Length .
SectionSkew                   ==> :float .
TunnelShape                   ==> .
WaterScoop                    ==> .
XoverPt                       ==> :float :uint :float .

/* Format types */
TrackSections                 ==> :uint,NextIndex {:TrackSection} .
TrackSection                  ==> :uint,Index [:SectionSize [:SectionCurve|:SectionSkew] [:WaterScoop]] .
TrackShapes                   ==> :uint,NextIndex {:TrackShape} .
TrackShape                    ==> :uint,Index [:FileName {:ClearanceDist|:CrossoverShape|:MainRoute|:ManualJunctionShape|:NumPaths|:RoadShape|:SectionIdx|:TunnelShape|:XoverPts}] .
XoverPts                      ==> :uint,Count {:XoverPt} .

EOF                           /* End of file */
