/* File format information */
FILE                          = :TrackSections :SectionIdx .
FILE_NAME                     = "Track Sections (Route)" .
FILE_EXT                      = "tsection.dat" .
FILE_TYPE                     = "T" .
FILE_TYPE_VER                 = "0" .

/* Base types */
SectionCurve                  ==> :uint .

/* Format types */
TrackSections                 ==> :uint,Count {:TrackSection} .
TrackSection                  ==> :SectionCurve :uint,ID :float :float .
SectionIdx                    ==> :uint,Count {:TrackPath} .
TrackPath                     ==> :uint :uint,Count {:uint} .

EOF                           /* End of file */
