//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimisEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2009-06-16")]
        public global::System.DateTime UpdateCheckCodePlexReleaseDate {
            get {
                return ((global::System.DateTime)(this["UpdateCheckCodePlexReleaseDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jgrmsts")]
        public string UpdateCheckCodePlexProjectUrl {
            get {
                return ((string)(this["UpdateCheckCodePlexProjectUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Simis Editor")]
        public string UpdateCheckCodePlexProjectName {
            get {
                return ((string)(this["UpdateCheckCodePlexProjectName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jgrmsts.codeplex.com/")]
        public string AboutHomepageUrl {
            get {
                return ((string)(this["AboutHomepageUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jgrmsts.codeplex.com/Release/ProjectReleases.aspx")]
        public string AboutUpdatesUrl {
            get {
                return ((string)(this["AboutUpdatesUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jgrmsts.codeplex.com/WorkItem/List.aspx")]
        public string AboutIssuesUrl {
            get {
                return ((string)(this["AboutIssuesUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jgrmsts.codeplex.com/Thread/List.aspx")]
        public string AboutDiscussionsUrl {
            get {
                return ((string)(this["AboutDiscussionsUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime UpdateCheckLastTime {
            get {
                return ((global::System.DateTime)(this["UpdateCheckLastTime"]));
            }
            set {
                this["UpdateCheckLastTime"] = value;
            }
        }
    }
}
